apiVersion: v1
kind: Service
metadata:
  name: flagger-prometheus
  namespace: flagger-system
spec:
  selector:
    app: flagger-prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090